// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Msg.proto

// Protobuf Java Version: 3.25.3
package io.piper.common.pojo.message.protoObj;

public interface CustomMsgBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protoObj.CustomMsgBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string data = 1;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <code>string data = 1;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
