// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Msg.proto

// Protobuf Java Version: 3.25.3
package io.piper.common.pojo.message.protoObj;

public interface ImageMsgBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protoObj.ImageMsgBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string url = 1;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 1;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>int32 size = 2;</code>
   * @return The size.
   */
  int getSize();

  /**
   * <code>int32 width = 3;</code>
   * @return The width.
   */
  int getWidth();

  /**
   * <code>int32 height = 4;</code>
   * @return The height.
   */
  int getHeight();
}
