// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Msg.proto

// Protobuf Java Version: 3.25.3
package io.piper.common.pojo.message.protoObj;

public interface LocationMsgBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protoObj.LocationMsgBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string address = 1;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 1;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>double latitude = 2;</code>
   * @return The latitude.
   */
  double getLatitude();

  /**
   * <code>double longitude = 3;</code>
   * @return The longitude.
   */
  double getLongitude();
}
