// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Msg.proto

// Protobuf Java Version: 3.25.3
package io.piper.common.pojo.message.protoObj;

/**
 * Protobuf type {@code protoObj.Msg}
 */
public final class Msg extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protoObj.Msg)
    MsgOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Msg.newBuilder() to construct.
  private Msg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Msg() {
    to_ = emptyLongList();
    text_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Msg();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.piper.common.pojo.message.protoObj.PBOuterClass.internal_static_protoObj_Msg_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.piper.common.pojo.message.protoObj.PBOuterClass.internal_static_protoObj_Msg_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.piper.common.pojo.message.protoObj.Msg.class, io.piper.common.pojo.message.protoObj.Msg.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private long id_ = 0L;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  private int type_ = 0;
  /**
   * <code>int32 type = 2;</code>
   * @return The type.
   */
  @java.lang.Override
  public int getType() {
    return type_;
  }

  public static final int CHATTYPE_FIELD_NUMBER = 3;
  private int chatType_ = 0;
  /**
   * <code>int32 chatType = 3;</code>
   * @return The chatType.
   */
  @java.lang.Override
  public int getChatType() {
    return chatType_;
  }

  public static final int CHATID_FIELD_NUMBER = 4;
  private long chatId_ = 0L;
  /**
   * <code>int64 chatId = 4;</code>
   * @return The chatId.
   */
  @java.lang.Override
  public long getChatId() {
    return chatId_;
  }

  public static final int FROM_FIELD_NUMBER = 5;
  private long from_ = 0L;
  /**
   * <code>int64 from = 5;</code>
   * @return The from.
   */
  @java.lang.Override
  public long getFrom() {
    return from_;
  }

  public static final int TO_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.LongList to_ =
      emptyLongList();
  /**
   * <code>repeated int64 to = 6;</code>
   * @return A list containing the to.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getToList() {
    return to_;
  }
  /**
   * <code>repeated int64 to = 6;</code>
   * @return The count of to.
   */
  public int getToCount() {
    return to_.size();
  }
  /**
   * <code>repeated int64 to = 6;</code>
   * @param index The index of the element to return.
   * @return The to at the given index.
   */
  public long getTo(int index) {
    return to_.getLong(index);
  }
  private int toMemoizedSerializedSize = -1;

  public static final int TEXT_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object text_ = "";
  /**
   * <code>string text = 7;</code>
   * @return The text.
   */
  @java.lang.Override
  public java.lang.String getText() {
    java.lang.Object ref = text_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      text_ = s;
      return s;
    }
  }
  /**
   * <code>string text = 7;</code>
   * @return The bytes for text.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTextBytes() {
    java.lang.Object ref = text_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      text_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIME_FIELD_NUMBER = 8;
  private long time_ = 0L;
  /**
   * <code>int64 time = 8;</code>
   * @return The time.
   */
  @java.lang.Override
  public long getTime() {
    return time_;
  }

  public static final int IMAGEMSGBODY_FIELD_NUMBER = 9;
  private io.piper.common.pojo.message.protoObj.ImageMsgBody imageMsgBody_;
  /**
   * <code>.protoObj.ImageMsgBody imageMsgBody = 9;</code>
   * @return Whether the imageMsgBody field is set.
   */
  @java.lang.Override
  public boolean hasImageMsgBody() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.protoObj.ImageMsgBody imageMsgBody = 9;</code>
   * @return The imageMsgBody.
   */
  @java.lang.Override
  public io.piper.common.pojo.message.protoObj.ImageMsgBody getImageMsgBody() {
    return imageMsgBody_ == null ? io.piper.common.pojo.message.protoObj.ImageMsgBody.getDefaultInstance() : imageMsgBody_;
  }
  /**
   * <code>.protoObj.ImageMsgBody imageMsgBody = 9;</code>
   */
  @java.lang.Override
  public io.piper.common.pojo.message.protoObj.ImageMsgBodyOrBuilder getImageMsgBodyOrBuilder() {
    return imageMsgBody_ == null ? io.piper.common.pojo.message.protoObj.ImageMsgBody.getDefaultInstance() : imageMsgBody_;
  }

  public static final int AUDIOMSGBODY_FIELD_NUMBER = 10;
  private io.piper.common.pojo.message.protoObj.AudioMsgBody audioMsgBody_;
  /**
   * <code>.protoObj.AudioMsgBody audioMsgBody = 10;</code>
   * @return Whether the audioMsgBody field is set.
   */
  @java.lang.Override
  public boolean hasAudioMsgBody() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.protoObj.AudioMsgBody audioMsgBody = 10;</code>
   * @return The audioMsgBody.
   */
  @java.lang.Override
  public io.piper.common.pojo.message.protoObj.AudioMsgBody getAudioMsgBody() {
    return audioMsgBody_ == null ? io.piper.common.pojo.message.protoObj.AudioMsgBody.getDefaultInstance() : audioMsgBody_;
  }
  /**
   * <code>.protoObj.AudioMsgBody audioMsgBody = 10;</code>
   */
  @java.lang.Override
  public io.piper.common.pojo.message.protoObj.AudioMsgBodyOrBuilder getAudioMsgBodyOrBuilder() {
    return audioMsgBody_ == null ? io.piper.common.pojo.message.protoObj.AudioMsgBody.getDefaultInstance() : audioMsgBody_;
  }

  public static final int VIDEOMSGBODY_FIELD_NUMBER = 11;
  private io.piper.common.pojo.message.protoObj.VideoMsgBody videoMsgBody_;
  /**
   * <code>.protoObj.VideoMsgBody videoMsgBody = 11;</code>
   * @return Whether the videoMsgBody field is set.
   */
  @java.lang.Override
  public boolean hasVideoMsgBody() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.protoObj.VideoMsgBody videoMsgBody = 11;</code>
   * @return The videoMsgBody.
   */
  @java.lang.Override
  public io.piper.common.pojo.message.protoObj.VideoMsgBody getVideoMsgBody() {
    return videoMsgBody_ == null ? io.piper.common.pojo.message.protoObj.VideoMsgBody.getDefaultInstance() : videoMsgBody_;
  }
  /**
   * <code>.protoObj.VideoMsgBody videoMsgBody = 11;</code>
   */
  @java.lang.Override
  public io.piper.common.pojo.message.protoObj.VideoMsgBodyOrBuilder getVideoMsgBodyOrBuilder() {
    return videoMsgBody_ == null ? io.piper.common.pojo.message.protoObj.VideoMsgBody.getDefaultInstance() : videoMsgBody_;
  }

  public static final int FILEMSGBODY_FIELD_NUMBER = 12;
  private io.piper.common.pojo.message.protoObj.FileMsgBody fileMsgBody_;
  /**
   * <code>.protoObj.FileMsgBody fileMsgBody = 12;</code>
   * @return Whether the fileMsgBody field is set.
   */
  @java.lang.Override
  public boolean hasFileMsgBody() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>.protoObj.FileMsgBody fileMsgBody = 12;</code>
   * @return The fileMsgBody.
   */
  @java.lang.Override
  public io.piper.common.pojo.message.protoObj.FileMsgBody getFileMsgBody() {
    return fileMsgBody_ == null ? io.piper.common.pojo.message.protoObj.FileMsgBody.getDefaultInstance() : fileMsgBody_;
  }
  /**
   * <code>.protoObj.FileMsgBody fileMsgBody = 12;</code>
   */
  @java.lang.Override
  public io.piper.common.pojo.message.protoObj.FileMsgBodyOrBuilder getFileMsgBodyOrBuilder() {
    return fileMsgBody_ == null ? io.piper.common.pojo.message.protoObj.FileMsgBody.getDefaultInstance() : fileMsgBody_;
  }

  public static final int LOCATIONMSGBODY_FIELD_NUMBER = 13;
  private io.piper.common.pojo.message.protoObj.LocationMsgBody locationMsgBody_;
  /**
   * <code>.protoObj.LocationMsgBody locationMsgBody = 13;</code>
   * @return Whether the locationMsgBody field is set.
   */
  @java.lang.Override
  public boolean hasLocationMsgBody() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>.protoObj.LocationMsgBody locationMsgBody = 13;</code>
   * @return The locationMsgBody.
   */
  @java.lang.Override
  public io.piper.common.pojo.message.protoObj.LocationMsgBody getLocationMsgBody() {
    return locationMsgBody_ == null ? io.piper.common.pojo.message.protoObj.LocationMsgBody.getDefaultInstance() : locationMsgBody_;
  }
  /**
   * <code>.protoObj.LocationMsgBody locationMsgBody = 13;</code>
   */
  @java.lang.Override
  public io.piper.common.pojo.message.protoObj.LocationMsgBodyOrBuilder getLocationMsgBodyOrBuilder() {
    return locationMsgBody_ == null ? io.piper.common.pojo.message.protoObj.LocationMsgBody.getDefaultInstance() : locationMsgBody_;
  }

  public static final int CUSTOMMSGBODY_FIELD_NUMBER = 14;
  private io.piper.common.pojo.message.protoObj.CustomMsgBody customMsgBody_;
  /**
   * <code>.protoObj.CustomMsgBody customMsgBody = 14;</code>
   * @return Whether the customMsgBody field is set.
   */
  @java.lang.Override
  public boolean hasCustomMsgBody() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>.protoObj.CustomMsgBody customMsgBody = 14;</code>
   * @return The customMsgBody.
   */
  @java.lang.Override
  public io.piper.common.pojo.message.protoObj.CustomMsgBody getCustomMsgBody() {
    return customMsgBody_ == null ? io.piper.common.pojo.message.protoObj.CustomMsgBody.getDefaultInstance() : customMsgBody_;
  }
  /**
   * <code>.protoObj.CustomMsgBody customMsgBody = 14;</code>
   */
  @java.lang.Override
  public io.piper.common.pojo.message.protoObj.CustomMsgBodyOrBuilder getCustomMsgBodyOrBuilder() {
    return customMsgBody_ == null ? io.piper.common.pojo.message.protoObj.CustomMsgBody.getDefaultInstance() : customMsgBody_;
  }

  public static final int BODY_FIELD_NUMBER = 15;
  private com.google.protobuf.Any body_;
  /**
   * <code>.google.protobuf.Any body = 15;</code>
   * @return Whether the body field is set.
   */
  @java.lang.Override
  public boolean hasBody() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>.google.protobuf.Any body = 15;</code>
   * @return The body.
   */
  @java.lang.Override
  public com.google.protobuf.Any getBody() {
    return body_ == null ? com.google.protobuf.Any.getDefaultInstance() : body_;
  }
  /**
   * <code>.google.protobuf.Any body = 15;</code>
   */
  @java.lang.Override
  public com.google.protobuf.AnyOrBuilder getBodyOrBuilder() {
    return body_ == null ? com.google.protobuf.Any.getDefaultInstance() : body_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (type_ != 0) {
      output.writeInt32(2, type_);
    }
    if (chatType_ != 0) {
      output.writeInt32(3, chatType_);
    }
    if (chatId_ != 0L) {
      output.writeInt64(4, chatId_);
    }
    if (from_ != 0L) {
      output.writeInt64(5, from_);
    }
    if (getToList().size() > 0) {
      output.writeUInt32NoTag(50);
      output.writeUInt32NoTag(toMemoizedSerializedSize);
    }
    for (int i = 0; i < to_.size(); i++) {
      output.writeInt64NoTag(to_.getLong(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(text_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, text_);
    }
    if (time_ != 0L) {
      output.writeInt64(8, time_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(9, getImageMsgBody());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(10, getAudioMsgBody());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(11, getVideoMsgBody());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(12, getFileMsgBody());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeMessage(13, getLocationMsgBody());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeMessage(14, getCustomMsgBody());
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeMessage(15, getBody());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (type_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, type_);
    }
    if (chatType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, chatType_);
    }
    if (chatId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, chatId_);
    }
    if (from_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, from_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < to_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(to_.getLong(i));
      }
      size += dataSize;
      if (!getToList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      toMemoizedSerializedSize = dataSize;
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(text_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, text_);
    }
    if (time_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, time_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getImageMsgBody());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getAudioMsgBody());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, getVideoMsgBody());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, getFileMsgBody());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(13, getLocationMsgBody());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(14, getCustomMsgBody());
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(15, getBody());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.piper.common.pojo.message.protoObj.Msg)) {
      return super.equals(obj);
    }
    io.piper.common.pojo.message.protoObj.Msg other = (io.piper.common.pojo.message.protoObj.Msg) obj;

    if (getId()
        != other.getId()) return false;
    if (getType()
        != other.getType()) return false;
    if (getChatType()
        != other.getChatType()) return false;
    if (getChatId()
        != other.getChatId()) return false;
    if (getFrom()
        != other.getFrom()) return false;
    if (!getToList()
        .equals(other.getToList())) return false;
    if (!getText()
        .equals(other.getText())) return false;
    if (getTime()
        != other.getTime()) return false;
    if (hasImageMsgBody() != other.hasImageMsgBody()) return false;
    if (hasImageMsgBody()) {
      if (!getImageMsgBody()
          .equals(other.getImageMsgBody())) return false;
    }
    if (hasAudioMsgBody() != other.hasAudioMsgBody()) return false;
    if (hasAudioMsgBody()) {
      if (!getAudioMsgBody()
          .equals(other.getAudioMsgBody())) return false;
    }
    if (hasVideoMsgBody() != other.hasVideoMsgBody()) return false;
    if (hasVideoMsgBody()) {
      if (!getVideoMsgBody()
          .equals(other.getVideoMsgBody())) return false;
    }
    if (hasFileMsgBody() != other.hasFileMsgBody()) return false;
    if (hasFileMsgBody()) {
      if (!getFileMsgBody()
          .equals(other.getFileMsgBody())) return false;
    }
    if (hasLocationMsgBody() != other.hasLocationMsgBody()) return false;
    if (hasLocationMsgBody()) {
      if (!getLocationMsgBody()
          .equals(other.getLocationMsgBody())) return false;
    }
    if (hasCustomMsgBody() != other.hasCustomMsgBody()) return false;
    if (hasCustomMsgBody()) {
      if (!getCustomMsgBody()
          .equals(other.getCustomMsgBody())) return false;
    }
    if (hasBody() != other.hasBody()) return false;
    if (hasBody()) {
      if (!getBody()
          .equals(other.getBody())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType();
    hash = (37 * hash) + CHATTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getChatType();
    hash = (37 * hash) + CHATID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getChatId());
    hash = (37 * hash) + FROM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFrom());
    if (getToCount() > 0) {
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + getToList().hashCode();
    }
    hash = (37 * hash) + TEXT_FIELD_NUMBER;
    hash = (53 * hash) + getText().hashCode();
    hash = (37 * hash) + TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTime());
    if (hasImageMsgBody()) {
      hash = (37 * hash) + IMAGEMSGBODY_FIELD_NUMBER;
      hash = (53 * hash) + getImageMsgBody().hashCode();
    }
    if (hasAudioMsgBody()) {
      hash = (37 * hash) + AUDIOMSGBODY_FIELD_NUMBER;
      hash = (53 * hash) + getAudioMsgBody().hashCode();
    }
    if (hasVideoMsgBody()) {
      hash = (37 * hash) + VIDEOMSGBODY_FIELD_NUMBER;
      hash = (53 * hash) + getVideoMsgBody().hashCode();
    }
    if (hasFileMsgBody()) {
      hash = (37 * hash) + FILEMSGBODY_FIELD_NUMBER;
      hash = (53 * hash) + getFileMsgBody().hashCode();
    }
    if (hasLocationMsgBody()) {
      hash = (37 * hash) + LOCATIONMSGBODY_FIELD_NUMBER;
      hash = (53 * hash) + getLocationMsgBody().hashCode();
    }
    if (hasCustomMsgBody()) {
      hash = (37 * hash) + CUSTOMMSGBODY_FIELD_NUMBER;
      hash = (53 * hash) + getCustomMsgBody().hashCode();
    }
    if (hasBody()) {
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.piper.common.pojo.message.protoObj.Msg parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.piper.common.pojo.message.protoObj.Msg parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.piper.common.pojo.message.protoObj.Msg parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.piper.common.pojo.message.protoObj.Msg parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.piper.common.pojo.message.protoObj.Msg parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.piper.common.pojo.message.protoObj.Msg parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.piper.common.pojo.message.protoObj.Msg parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.piper.common.pojo.message.protoObj.Msg parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.piper.common.pojo.message.protoObj.Msg parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.piper.common.pojo.message.protoObj.Msg parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.piper.common.pojo.message.protoObj.Msg parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.piper.common.pojo.message.protoObj.Msg parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.piper.common.pojo.message.protoObj.Msg prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protoObj.Msg}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protoObj.Msg)
      io.piper.common.pojo.message.protoObj.MsgOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.piper.common.pojo.message.protoObj.PBOuterClass.internal_static_protoObj_Msg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.piper.common.pojo.message.protoObj.PBOuterClass.internal_static_protoObj_Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.piper.common.pojo.message.protoObj.Msg.class, io.piper.common.pojo.message.protoObj.Msg.Builder.class);
    }

    // Construct using io.piper.common.pojo.message.protoObj.Msg.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getImageMsgBodyFieldBuilder();
        getAudioMsgBodyFieldBuilder();
        getVideoMsgBodyFieldBuilder();
        getFileMsgBodyFieldBuilder();
        getLocationMsgBodyFieldBuilder();
        getCustomMsgBodyFieldBuilder();
        getBodyFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0L;
      type_ = 0;
      chatType_ = 0;
      chatId_ = 0L;
      from_ = 0L;
      to_ = emptyLongList();
      text_ = "";
      time_ = 0L;
      imageMsgBody_ = null;
      if (imageMsgBodyBuilder_ != null) {
        imageMsgBodyBuilder_.dispose();
        imageMsgBodyBuilder_ = null;
      }
      audioMsgBody_ = null;
      if (audioMsgBodyBuilder_ != null) {
        audioMsgBodyBuilder_.dispose();
        audioMsgBodyBuilder_ = null;
      }
      videoMsgBody_ = null;
      if (videoMsgBodyBuilder_ != null) {
        videoMsgBodyBuilder_.dispose();
        videoMsgBodyBuilder_ = null;
      }
      fileMsgBody_ = null;
      if (fileMsgBodyBuilder_ != null) {
        fileMsgBodyBuilder_.dispose();
        fileMsgBodyBuilder_ = null;
      }
      locationMsgBody_ = null;
      if (locationMsgBodyBuilder_ != null) {
        locationMsgBodyBuilder_.dispose();
        locationMsgBodyBuilder_ = null;
      }
      customMsgBody_ = null;
      if (customMsgBodyBuilder_ != null) {
        customMsgBodyBuilder_.dispose();
        customMsgBodyBuilder_ = null;
      }
      body_ = null;
      if (bodyBuilder_ != null) {
        bodyBuilder_.dispose();
        bodyBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.piper.common.pojo.message.protoObj.PBOuterClass.internal_static_protoObj_Msg_descriptor;
    }

    @java.lang.Override
    public io.piper.common.pojo.message.protoObj.Msg getDefaultInstanceForType() {
      return io.piper.common.pojo.message.protoObj.Msg.getDefaultInstance();
    }

    @java.lang.Override
    public io.piper.common.pojo.message.protoObj.Msg build() {
      io.piper.common.pojo.message.protoObj.Msg result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.piper.common.pojo.message.protoObj.Msg buildPartial() {
      io.piper.common.pojo.message.protoObj.Msg result = new io.piper.common.pojo.message.protoObj.Msg(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.piper.common.pojo.message.protoObj.Msg result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.chatType_ = chatType_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.chatId_ = chatId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.from_ = from_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        to_.makeImmutable();
        result.to_ = to_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.text_ = text_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.time_ = time_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.imageMsgBody_ = imageMsgBodyBuilder_ == null
            ? imageMsgBody_
            : imageMsgBodyBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.audioMsgBody_ = audioMsgBodyBuilder_ == null
            ? audioMsgBody_
            : audioMsgBodyBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.videoMsgBody_ = videoMsgBodyBuilder_ == null
            ? videoMsgBody_
            : videoMsgBodyBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.fileMsgBody_ = fileMsgBodyBuilder_ == null
            ? fileMsgBody_
            : fileMsgBodyBuilder_.build();
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.locationMsgBody_ = locationMsgBodyBuilder_ == null
            ? locationMsgBody_
            : locationMsgBodyBuilder_.build();
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.customMsgBody_ = customMsgBodyBuilder_ == null
            ? customMsgBody_
            : customMsgBodyBuilder_.build();
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.body_ = bodyBuilder_ == null
            ? body_
            : bodyBuilder_.build();
        to_bitField0_ |= 0x00000040;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.piper.common.pojo.message.protoObj.Msg) {
        return mergeFrom((io.piper.common.pojo.message.protoObj.Msg)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.piper.common.pojo.message.protoObj.Msg other) {
      if (other == io.piper.common.pojo.message.protoObj.Msg.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.getType() != 0) {
        setType(other.getType());
      }
      if (other.getChatType() != 0) {
        setChatType(other.getChatType());
      }
      if (other.getChatId() != 0L) {
        setChatId(other.getChatId());
      }
      if (other.getFrom() != 0L) {
        setFrom(other.getFrom());
      }
      if (!other.to_.isEmpty()) {
        if (to_.isEmpty()) {
          to_ = other.to_;
          to_.makeImmutable();
          bitField0_ |= 0x00000020;
        } else {
          ensureToIsMutable();
          to_.addAll(other.to_);
        }
        onChanged();
      }
      if (!other.getText().isEmpty()) {
        text_ = other.text_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (other.getTime() != 0L) {
        setTime(other.getTime());
      }
      if (other.hasImageMsgBody()) {
        mergeImageMsgBody(other.getImageMsgBody());
      }
      if (other.hasAudioMsgBody()) {
        mergeAudioMsgBody(other.getAudioMsgBody());
      }
      if (other.hasVideoMsgBody()) {
        mergeVideoMsgBody(other.getVideoMsgBody());
      }
      if (other.hasFileMsgBody()) {
        mergeFileMsgBody(other.getFileMsgBody());
      }
      if (other.hasLocationMsgBody()) {
        mergeLocationMsgBody(other.getLocationMsgBody());
      }
      if (other.hasCustomMsgBody()) {
        mergeCustomMsgBody(other.getCustomMsgBody());
      }
      if (other.hasBody()) {
        mergeBody(other.getBody());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              type_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              chatType_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              chatId_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              from_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              long v = input.readInt64();
              ensureToIsMutable();
              to_.addLong(v);
              break;
            } // case 48
            case 50: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureToIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                to_.addLong(input.readInt64());
              }
              input.popLimit(limit);
              break;
            } // case 50
            case 58: {
              text_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 64: {
              time_ = input.readInt64();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 74: {
              input.readMessage(
                  getImageMsgBodyFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              input.readMessage(
                  getAudioMsgBodyFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 90: {
              input.readMessage(
                  getVideoMsgBodyFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            case 98: {
              input.readMessage(
                  getFileMsgBodyFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000800;
              break;
            } // case 98
            case 106: {
              input.readMessage(
                  getLocationMsgBodyFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00001000;
              break;
            } // case 106
            case 114: {
              input.readMessage(
                  getCustomMsgBodyFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00002000;
              break;
            } // case 114
            case 122: {
              input.readMessage(
                  getBodyFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00004000;
              break;
            } // case 122
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    private int type_ ;
    /**
     * <code>int32 type = 2;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }
    /**
     * <code>int32 type = 2;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(int value) {

      type_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      type_ = 0;
      onChanged();
      return this;
    }

    private int chatType_ ;
    /**
     * <code>int32 chatType = 3;</code>
     * @return The chatType.
     */
    @java.lang.Override
    public int getChatType() {
      return chatType_;
    }
    /**
     * <code>int32 chatType = 3;</code>
     * @param value The chatType to set.
     * @return This builder for chaining.
     */
    public Builder setChatType(int value) {

      chatType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 chatType = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearChatType() {
      bitField0_ = (bitField0_ & ~0x00000004);
      chatType_ = 0;
      onChanged();
      return this;
    }

    private long chatId_ ;
    /**
     * <code>int64 chatId = 4;</code>
     * @return The chatId.
     */
    @java.lang.Override
    public long getChatId() {
      return chatId_;
    }
    /**
     * <code>int64 chatId = 4;</code>
     * @param value The chatId to set.
     * @return This builder for chaining.
     */
    public Builder setChatId(long value) {

      chatId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 chatId = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearChatId() {
      bitField0_ = (bitField0_ & ~0x00000008);
      chatId_ = 0L;
      onChanged();
      return this;
    }

    private long from_ ;
    /**
     * <code>int64 from = 5;</code>
     * @return The from.
     */
    @java.lang.Override
    public long getFrom() {
      return from_;
    }
    /**
     * <code>int64 from = 5;</code>
     * @param value The from to set.
     * @return This builder for chaining.
     */
    public Builder setFrom(long value) {

      from_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int64 from = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearFrom() {
      bitField0_ = (bitField0_ & ~0x00000010);
      from_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList to_ = emptyLongList();
    private void ensureToIsMutable() {
      if (!to_.isModifiable()) {
        to_ = makeMutableCopy(to_);
      }
      bitField0_ |= 0x00000020;
    }
    /**
     * <code>repeated int64 to = 6;</code>
     * @return A list containing the to.
     */
    public java.util.List<java.lang.Long>
        getToList() {
      to_.makeImmutable();
      return to_;
    }
    /**
     * <code>repeated int64 to = 6;</code>
     * @return The count of to.
     */
    public int getToCount() {
      return to_.size();
    }
    /**
     * <code>repeated int64 to = 6;</code>
     * @param index The index of the element to return.
     * @return The to at the given index.
     */
    public long getTo(int index) {
      return to_.getLong(index);
    }
    /**
     * <code>repeated int64 to = 6;</code>
     * @param index The index to set the value at.
     * @param value The to to set.
     * @return This builder for chaining.
     */
    public Builder setTo(
        int index, long value) {

      ensureToIsMutable();
      to_.setLong(index, value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 to = 6;</code>
     * @param value The to to add.
     * @return This builder for chaining.
     */
    public Builder addTo(long value) {

      ensureToIsMutable();
      to_.addLong(value);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 to = 6;</code>
     * @param values The to to add.
     * @return This builder for chaining.
     */
    public Builder addAllTo(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureToIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, to_);
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 to = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTo() {
      to_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }

    private java.lang.Object text_ = "";
    /**
     * <code>string text = 7;</code>
     * @return The text.
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string text = 7;</code>
     * @return The bytes for text.
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string text = 7;</code>
     * @param value The text to set.
     * @return This builder for chaining.
     */
    public Builder setText(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      text_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string text = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearText() {
      text_ = getDefaultInstance().getText();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string text = 7;</code>
     * @param value The bytes for text to set.
     * @return This builder for chaining.
     */
    public Builder setTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      text_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private long time_ ;
    /**
     * <code>int64 time = 8;</code>
     * @return The time.
     */
    @java.lang.Override
    public long getTime() {
      return time_;
    }
    /**
     * <code>int64 time = 8;</code>
     * @param value The time to set.
     * @return This builder for chaining.
     */
    public Builder setTime(long value) {

      time_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>int64 time = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearTime() {
      bitField0_ = (bitField0_ & ~0x00000080);
      time_ = 0L;
      onChanged();
      return this;
    }

    private io.piper.common.pojo.message.protoObj.ImageMsgBody imageMsgBody_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.piper.common.pojo.message.protoObj.ImageMsgBody, io.piper.common.pojo.message.protoObj.ImageMsgBody.Builder, io.piper.common.pojo.message.protoObj.ImageMsgBodyOrBuilder> imageMsgBodyBuilder_;
    /**
     * <code>.protoObj.ImageMsgBody imageMsgBody = 9;</code>
     * @return Whether the imageMsgBody field is set.
     */
    public boolean hasImageMsgBody() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>.protoObj.ImageMsgBody imageMsgBody = 9;</code>
     * @return The imageMsgBody.
     */
    public io.piper.common.pojo.message.protoObj.ImageMsgBody getImageMsgBody() {
      if (imageMsgBodyBuilder_ == null) {
        return imageMsgBody_ == null ? io.piper.common.pojo.message.protoObj.ImageMsgBody.getDefaultInstance() : imageMsgBody_;
      } else {
        return imageMsgBodyBuilder_.getMessage();
      }
    }
    /**
     * <code>.protoObj.ImageMsgBody imageMsgBody = 9;</code>
     */
    public Builder setImageMsgBody(io.piper.common.pojo.message.protoObj.ImageMsgBody value) {
      if (imageMsgBodyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        imageMsgBody_ = value;
      } else {
        imageMsgBodyBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.protoObj.ImageMsgBody imageMsgBody = 9;</code>
     */
    public Builder setImageMsgBody(
        io.piper.common.pojo.message.protoObj.ImageMsgBody.Builder builderForValue) {
      if (imageMsgBodyBuilder_ == null) {
        imageMsgBody_ = builderForValue.build();
      } else {
        imageMsgBodyBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.protoObj.ImageMsgBody imageMsgBody = 9;</code>
     */
    public Builder mergeImageMsgBody(io.piper.common.pojo.message.protoObj.ImageMsgBody value) {
      if (imageMsgBodyBuilder_ == null) {
        if (((bitField0_ & 0x00000100) != 0) &&
          imageMsgBody_ != null &&
          imageMsgBody_ != io.piper.common.pojo.message.protoObj.ImageMsgBody.getDefaultInstance()) {
          getImageMsgBodyBuilder().mergeFrom(value);
        } else {
          imageMsgBody_ = value;
        }
      } else {
        imageMsgBodyBuilder_.mergeFrom(value);
      }
      if (imageMsgBody_ != null) {
        bitField0_ |= 0x00000100;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.protoObj.ImageMsgBody imageMsgBody = 9;</code>
     */
    public Builder clearImageMsgBody() {
      bitField0_ = (bitField0_ & ~0x00000100);
      imageMsgBody_ = null;
      if (imageMsgBodyBuilder_ != null) {
        imageMsgBodyBuilder_.dispose();
        imageMsgBodyBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.protoObj.ImageMsgBody imageMsgBody = 9;</code>
     */
    public io.piper.common.pojo.message.protoObj.ImageMsgBody.Builder getImageMsgBodyBuilder() {
      bitField0_ |= 0x00000100;
      onChanged();
      return getImageMsgBodyFieldBuilder().getBuilder();
    }
    /**
     * <code>.protoObj.ImageMsgBody imageMsgBody = 9;</code>
     */
    public io.piper.common.pojo.message.protoObj.ImageMsgBodyOrBuilder getImageMsgBodyOrBuilder() {
      if (imageMsgBodyBuilder_ != null) {
        return imageMsgBodyBuilder_.getMessageOrBuilder();
      } else {
        return imageMsgBody_ == null ?
            io.piper.common.pojo.message.protoObj.ImageMsgBody.getDefaultInstance() : imageMsgBody_;
      }
    }
    /**
     * <code>.protoObj.ImageMsgBody imageMsgBody = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.piper.common.pojo.message.protoObj.ImageMsgBody, io.piper.common.pojo.message.protoObj.ImageMsgBody.Builder, io.piper.common.pojo.message.protoObj.ImageMsgBodyOrBuilder> 
        getImageMsgBodyFieldBuilder() {
      if (imageMsgBodyBuilder_ == null) {
        imageMsgBodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.piper.common.pojo.message.protoObj.ImageMsgBody, io.piper.common.pojo.message.protoObj.ImageMsgBody.Builder, io.piper.common.pojo.message.protoObj.ImageMsgBodyOrBuilder>(
                getImageMsgBody(),
                getParentForChildren(),
                isClean());
        imageMsgBody_ = null;
      }
      return imageMsgBodyBuilder_;
    }

    private io.piper.common.pojo.message.protoObj.AudioMsgBody audioMsgBody_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.piper.common.pojo.message.protoObj.AudioMsgBody, io.piper.common.pojo.message.protoObj.AudioMsgBody.Builder, io.piper.common.pojo.message.protoObj.AudioMsgBodyOrBuilder> audioMsgBodyBuilder_;
    /**
     * <code>.protoObj.AudioMsgBody audioMsgBody = 10;</code>
     * @return Whether the audioMsgBody field is set.
     */
    public boolean hasAudioMsgBody() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>.protoObj.AudioMsgBody audioMsgBody = 10;</code>
     * @return The audioMsgBody.
     */
    public io.piper.common.pojo.message.protoObj.AudioMsgBody getAudioMsgBody() {
      if (audioMsgBodyBuilder_ == null) {
        return audioMsgBody_ == null ? io.piper.common.pojo.message.protoObj.AudioMsgBody.getDefaultInstance() : audioMsgBody_;
      } else {
        return audioMsgBodyBuilder_.getMessage();
      }
    }
    /**
     * <code>.protoObj.AudioMsgBody audioMsgBody = 10;</code>
     */
    public Builder setAudioMsgBody(io.piper.common.pojo.message.protoObj.AudioMsgBody value) {
      if (audioMsgBodyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        audioMsgBody_ = value;
      } else {
        audioMsgBodyBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>.protoObj.AudioMsgBody audioMsgBody = 10;</code>
     */
    public Builder setAudioMsgBody(
        io.piper.common.pojo.message.protoObj.AudioMsgBody.Builder builderForValue) {
      if (audioMsgBodyBuilder_ == null) {
        audioMsgBody_ = builderForValue.build();
      } else {
        audioMsgBodyBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>.protoObj.AudioMsgBody audioMsgBody = 10;</code>
     */
    public Builder mergeAudioMsgBody(io.piper.common.pojo.message.protoObj.AudioMsgBody value) {
      if (audioMsgBodyBuilder_ == null) {
        if (((bitField0_ & 0x00000200) != 0) &&
          audioMsgBody_ != null &&
          audioMsgBody_ != io.piper.common.pojo.message.protoObj.AudioMsgBody.getDefaultInstance()) {
          getAudioMsgBodyBuilder().mergeFrom(value);
        } else {
          audioMsgBody_ = value;
        }
      } else {
        audioMsgBodyBuilder_.mergeFrom(value);
      }
      if (audioMsgBody_ != null) {
        bitField0_ |= 0x00000200;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.protoObj.AudioMsgBody audioMsgBody = 10;</code>
     */
    public Builder clearAudioMsgBody() {
      bitField0_ = (bitField0_ & ~0x00000200);
      audioMsgBody_ = null;
      if (audioMsgBodyBuilder_ != null) {
        audioMsgBodyBuilder_.dispose();
        audioMsgBodyBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.protoObj.AudioMsgBody audioMsgBody = 10;</code>
     */
    public io.piper.common.pojo.message.protoObj.AudioMsgBody.Builder getAudioMsgBodyBuilder() {
      bitField0_ |= 0x00000200;
      onChanged();
      return getAudioMsgBodyFieldBuilder().getBuilder();
    }
    /**
     * <code>.protoObj.AudioMsgBody audioMsgBody = 10;</code>
     */
    public io.piper.common.pojo.message.protoObj.AudioMsgBodyOrBuilder getAudioMsgBodyOrBuilder() {
      if (audioMsgBodyBuilder_ != null) {
        return audioMsgBodyBuilder_.getMessageOrBuilder();
      } else {
        return audioMsgBody_ == null ?
            io.piper.common.pojo.message.protoObj.AudioMsgBody.getDefaultInstance() : audioMsgBody_;
      }
    }
    /**
     * <code>.protoObj.AudioMsgBody audioMsgBody = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.piper.common.pojo.message.protoObj.AudioMsgBody, io.piper.common.pojo.message.protoObj.AudioMsgBody.Builder, io.piper.common.pojo.message.protoObj.AudioMsgBodyOrBuilder> 
        getAudioMsgBodyFieldBuilder() {
      if (audioMsgBodyBuilder_ == null) {
        audioMsgBodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.piper.common.pojo.message.protoObj.AudioMsgBody, io.piper.common.pojo.message.protoObj.AudioMsgBody.Builder, io.piper.common.pojo.message.protoObj.AudioMsgBodyOrBuilder>(
                getAudioMsgBody(),
                getParentForChildren(),
                isClean());
        audioMsgBody_ = null;
      }
      return audioMsgBodyBuilder_;
    }

    private io.piper.common.pojo.message.protoObj.VideoMsgBody videoMsgBody_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.piper.common.pojo.message.protoObj.VideoMsgBody, io.piper.common.pojo.message.protoObj.VideoMsgBody.Builder, io.piper.common.pojo.message.protoObj.VideoMsgBodyOrBuilder> videoMsgBodyBuilder_;
    /**
     * <code>.protoObj.VideoMsgBody videoMsgBody = 11;</code>
     * @return Whether the videoMsgBody field is set.
     */
    public boolean hasVideoMsgBody() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <code>.protoObj.VideoMsgBody videoMsgBody = 11;</code>
     * @return The videoMsgBody.
     */
    public io.piper.common.pojo.message.protoObj.VideoMsgBody getVideoMsgBody() {
      if (videoMsgBodyBuilder_ == null) {
        return videoMsgBody_ == null ? io.piper.common.pojo.message.protoObj.VideoMsgBody.getDefaultInstance() : videoMsgBody_;
      } else {
        return videoMsgBodyBuilder_.getMessage();
      }
    }
    /**
     * <code>.protoObj.VideoMsgBody videoMsgBody = 11;</code>
     */
    public Builder setVideoMsgBody(io.piper.common.pojo.message.protoObj.VideoMsgBody value) {
      if (videoMsgBodyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        videoMsgBody_ = value;
      } else {
        videoMsgBodyBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>.protoObj.VideoMsgBody videoMsgBody = 11;</code>
     */
    public Builder setVideoMsgBody(
        io.piper.common.pojo.message.protoObj.VideoMsgBody.Builder builderForValue) {
      if (videoMsgBodyBuilder_ == null) {
        videoMsgBody_ = builderForValue.build();
      } else {
        videoMsgBodyBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>.protoObj.VideoMsgBody videoMsgBody = 11;</code>
     */
    public Builder mergeVideoMsgBody(io.piper.common.pojo.message.protoObj.VideoMsgBody value) {
      if (videoMsgBodyBuilder_ == null) {
        if (((bitField0_ & 0x00000400) != 0) &&
          videoMsgBody_ != null &&
          videoMsgBody_ != io.piper.common.pojo.message.protoObj.VideoMsgBody.getDefaultInstance()) {
          getVideoMsgBodyBuilder().mergeFrom(value);
        } else {
          videoMsgBody_ = value;
        }
      } else {
        videoMsgBodyBuilder_.mergeFrom(value);
      }
      if (videoMsgBody_ != null) {
        bitField0_ |= 0x00000400;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.protoObj.VideoMsgBody videoMsgBody = 11;</code>
     */
    public Builder clearVideoMsgBody() {
      bitField0_ = (bitField0_ & ~0x00000400);
      videoMsgBody_ = null;
      if (videoMsgBodyBuilder_ != null) {
        videoMsgBodyBuilder_.dispose();
        videoMsgBodyBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.protoObj.VideoMsgBody videoMsgBody = 11;</code>
     */
    public io.piper.common.pojo.message.protoObj.VideoMsgBody.Builder getVideoMsgBodyBuilder() {
      bitField0_ |= 0x00000400;
      onChanged();
      return getVideoMsgBodyFieldBuilder().getBuilder();
    }
    /**
     * <code>.protoObj.VideoMsgBody videoMsgBody = 11;</code>
     */
    public io.piper.common.pojo.message.protoObj.VideoMsgBodyOrBuilder getVideoMsgBodyOrBuilder() {
      if (videoMsgBodyBuilder_ != null) {
        return videoMsgBodyBuilder_.getMessageOrBuilder();
      } else {
        return videoMsgBody_ == null ?
            io.piper.common.pojo.message.protoObj.VideoMsgBody.getDefaultInstance() : videoMsgBody_;
      }
    }
    /**
     * <code>.protoObj.VideoMsgBody videoMsgBody = 11;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.piper.common.pojo.message.protoObj.VideoMsgBody, io.piper.common.pojo.message.protoObj.VideoMsgBody.Builder, io.piper.common.pojo.message.protoObj.VideoMsgBodyOrBuilder> 
        getVideoMsgBodyFieldBuilder() {
      if (videoMsgBodyBuilder_ == null) {
        videoMsgBodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.piper.common.pojo.message.protoObj.VideoMsgBody, io.piper.common.pojo.message.protoObj.VideoMsgBody.Builder, io.piper.common.pojo.message.protoObj.VideoMsgBodyOrBuilder>(
                getVideoMsgBody(),
                getParentForChildren(),
                isClean());
        videoMsgBody_ = null;
      }
      return videoMsgBodyBuilder_;
    }

    private io.piper.common.pojo.message.protoObj.FileMsgBody fileMsgBody_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.piper.common.pojo.message.protoObj.FileMsgBody, io.piper.common.pojo.message.protoObj.FileMsgBody.Builder, io.piper.common.pojo.message.protoObj.FileMsgBodyOrBuilder> fileMsgBodyBuilder_;
    /**
     * <code>.protoObj.FileMsgBody fileMsgBody = 12;</code>
     * @return Whether the fileMsgBody field is set.
     */
    public boolean hasFileMsgBody() {
      return ((bitField0_ & 0x00000800) != 0);
    }
    /**
     * <code>.protoObj.FileMsgBody fileMsgBody = 12;</code>
     * @return The fileMsgBody.
     */
    public io.piper.common.pojo.message.protoObj.FileMsgBody getFileMsgBody() {
      if (fileMsgBodyBuilder_ == null) {
        return fileMsgBody_ == null ? io.piper.common.pojo.message.protoObj.FileMsgBody.getDefaultInstance() : fileMsgBody_;
      } else {
        return fileMsgBodyBuilder_.getMessage();
      }
    }
    /**
     * <code>.protoObj.FileMsgBody fileMsgBody = 12;</code>
     */
    public Builder setFileMsgBody(io.piper.common.pojo.message.protoObj.FileMsgBody value) {
      if (fileMsgBodyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        fileMsgBody_ = value;
      } else {
        fileMsgBodyBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>.protoObj.FileMsgBody fileMsgBody = 12;</code>
     */
    public Builder setFileMsgBody(
        io.piper.common.pojo.message.protoObj.FileMsgBody.Builder builderForValue) {
      if (fileMsgBodyBuilder_ == null) {
        fileMsgBody_ = builderForValue.build();
      } else {
        fileMsgBodyBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>.protoObj.FileMsgBody fileMsgBody = 12;</code>
     */
    public Builder mergeFileMsgBody(io.piper.common.pojo.message.protoObj.FileMsgBody value) {
      if (fileMsgBodyBuilder_ == null) {
        if (((bitField0_ & 0x00000800) != 0) &&
          fileMsgBody_ != null &&
          fileMsgBody_ != io.piper.common.pojo.message.protoObj.FileMsgBody.getDefaultInstance()) {
          getFileMsgBodyBuilder().mergeFrom(value);
        } else {
          fileMsgBody_ = value;
        }
      } else {
        fileMsgBodyBuilder_.mergeFrom(value);
      }
      if (fileMsgBody_ != null) {
        bitField0_ |= 0x00000800;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.protoObj.FileMsgBody fileMsgBody = 12;</code>
     */
    public Builder clearFileMsgBody() {
      bitField0_ = (bitField0_ & ~0x00000800);
      fileMsgBody_ = null;
      if (fileMsgBodyBuilder_ != null) {
        fileMsgBodyBuilder_.dispose();
        fileMsgBodyBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.protoObj.FileMsgBody fileMsgBody = 12;</code>
     */
    public io.piper.common.pojo.message.protoObj.FileMsgBody.Builder getFileMsgBodyBuilder() {
      bitField0_ |= 0x00000800;
      onChanged();
      return getFileMsgBodyFieldBuilder().getBuilder();
    }
    /**
     * <code>.protoObj.FileMsgBody fileMsgBody = 12;</code>
     */
    public io.piper.common.pojo.message.protoObj.FileMsgBodyOrBuilder getFileMsgBodyOrBuilder() {
      if (fileMsgBodyBuilder_ != null) {
        return fileMsgBodyBuilder_.getMessageOrBuilder();
      } else {
        return fileMsgBody_ == null ?
            io.piper.common.pojo.message.protoObj.FileMsgBody.getDefaultInstance() : fileMsgBody_;
      }
    }
    /**
     * <code>.protoObj.FileMsgBody fileMsgBody = 12;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.piper.common.pojo.message.protoObj.FileMsgBody, io.piper.common.pojo.message.protoObj.FileMsgBody.Builder, io.piper.common.pojo.message.protoObj.FileMsgBodyOrBuilder> 
        getFileMsgBodyFieldBuilder() {
      if (fileMsgBodyBuilder_ == null) {
        fileMsgBodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.piper.common.pojo.message.protoObj.FileMsgBody, io.piper.common.pojo.message.protoObj.FileMsgBody.Builder, io.piper.common.pojo.message.protoObj.FileMsgBodyOrBuilder>(
                getFileMsgBody(),
                getParentForChildren(),
                isClean());
        fileMsgBody_ = null;
      }
      return fileMsgBodyBuilder_;
    }

    private io.piper.common.pojo.message.protoObj.LocationMsgBody locationMsgBody_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.piper.common.pojo.message.protoObj.LocationMsgBody, io.piper.common.pojo.message.protoObj.LocationMsgBody.Builder, io.piper.common.pojo.message.protoObj.LocationMsgBodyOrBuilder> locationMsgBodyBuilder_;
    /**
     * <code>.protoObj.LocationMsgBody locationMsgBody = 13;</code>
     * @return Whether the locationMsgBody field is set.
     */
    public boolean hasLocationMsgBody() {
      return ((bitField0_ & 0x00001000) != 0);
    }
    /**
     * <code>.protoObj.LocationMsgBody locationMsgBody = 13;</code>
     * @return The locationMsgBody.
     */
    public io.piper.common.pojo.message.protoObj.LocationMsgBody getLocationMsgBody() {
      if (locationMsgBodyBuilder_ == null) {
        return locationMsgBody_ == null ? io.piper.common.pojo.message.protoObj.LocationMsgBody.getDefaultInstance() : locationMsgBody_;
      } else {
        return locationMsgBodyBuilder_.getMessage();
      }
    }
    /**
     * <code>.protoObj.LocationMsgBody locationMsgBody = 13;</code>
     */
    public Builder setLocationMsgBody(io.piper.common.pojo.message.protoObj.LocationMsgBody value) {
      if (locationMsgBodyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        locationMsgBody_ = value;
      } else {
        locationMsgBodyBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>.protoObj.LocationMsgBody locationMsgBody = 13;</code>
     */
    public Builder setLocationMsgBody(
        io.piper.common.pojo.message.protoObj.LocationMsgBody.Builder builderForValue) {
      if (locationMsgBodyBuilder_ == null) {
        locationMsgBody_ = builderForValue.build();
      } else {
        locationMsgBodyBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>.protoObj.LocationMsgBody locationMsgBody = 13;</code>
     */
    public Builder mergeLocationMsgBody(io.piper.common.pojo.message.protoObj.LocationMsgBody value) {
      if (locationMsgBodyBuilder_ == null) {
        if (((bitField0_ & 0x00001000) != 0) &&
          locationMsgBody_ != null &&
          locationMsgBody_ != io.piper.common.pojo.message.protoObj.LocationMsgBody.getDefaultInstance()) {
          getLocationMsgBodyBuilder().mergeFrom(value);
        } else {
          locationMsgBody_ = value;
        }
      } else {
        locationMsgBodyBuilder_.mergeFrom(value);
      }
      if (locationMsgBody_ != null) {
        bitField0_ |= 0x00001000;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.protoObj.LocationMsgBody locationMsgBody = 13;</code>
     */
    public Builder clearLocationMsgBody() {
      bitField0_ = (bitField0_ & ~0x00001000);
      locationMsgBody_ = null;
      if (locationMsgBodyBuilder_ != null) {
        locationMsgBodyBuilder_.dispose();
        locationMsgBodyBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.protoObj.LocationMsgBody locationMsgBody = 13;</code>
     */
    public io.piper.common.pojo.message.protoObj.LocationMsgBody.Builder getLocationMsgBodyBuilder() {
      bitField0_ |= 0x00001000;
      onChanged();
      return getLocationMsgBodyFieldBuilder().getBuilder();
    }
    /**
     * <code>.protoObj.LocationMsgBody locationMsgBody = 13;</code>
     */
    public io.piper.common.pojo.message.protoObj.LocationMsgBodyOrBuilder getLocationMsgBodyOrBuilder() {
      if (locationMsgBodyBuilder_ != null) {
        return locationMsgBodyBuilder_.getMessageOrBuilder();
      } else {
        return locationMsgBody_ == null ?
            io.piper.common.pojo.message.protoObj.LocationMsgBody.getDefaultInstance() : locationMsgBody_;
      }
    }
    /**
     * <code>.protoObj.LocationMsgBody locationMsgBody = 13;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.piper.common.pojo.message.protoObj.LocationMsgBody, io.piper.common.pojo.message.protoObj.LocationMsgBody.Builder, io.piper.common.pojo.message.protoObj.LocationMsgBodyOrBuilder> 
        getLocationMsgBodyFieldBuilder() {
      if (locationMsgBodyBuilder_ == null) {
        locationMsgBodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.piper.common.pojo.message.protoObj.LocationMsgBody, io.piper.common.pojo.message.protoObj.LocationMsgBody.Builder, io.piper.common.pojo.message.protoObj.LocationMsgBodyOrBuilder>(
                getLocationMsgBody(),
                getParentForChildren(),
                isClean());
        locationMsgBody_ = null;
      }
      return locationMsgBodyBuilder_;
    }

    private io.piper.common.pojo.message.protoObj.CustomMsgBody customMsgBody_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.piper.common.pojo.message.protoObj.CustomMsgBody, io.piper.common.pojo.message.protoObj.CustomMsgBody.Builder, io.piper.common.pojo.message.protoObj.CustomMsgBodyOrBuilder> customMsgBodyBuilder_;
    /**
     * <code>.protoObj.CustomMsgBody customMsgBody = 14;</code>
     * @return Whether the customMsgBody field is set.
     */
    public boolean hasCustomMsgBody() {
      return ((bitField0_ & 0x00002000) != 0);
    }
    /**
     * <code>.protoObj.CustomMsgBody customMsgBody = 14;</code>
     * @return The customMsgBody.
     */
    public io.piper.common.pojo.message.protoObj.CustomMsgBody getCustomMsgBody() {
      if (customMsgBodyBuilder_ == null) {
        return customMsgBody_ == null ? io.piper.common.pojo.message.protoObj.CustomMsgBody.getDefaultInstance() : customMsgBody_;
      } else {
        return customMsgBodyBuilder_.getMessage();
      }
    }
    /**
     * <code>.protoObj.CustomMsgBody customMsgBody = 14;</code>
     */
    public Builder setCustomMsgBody(io.piper.common.pojo.message.protoObj.CustomMsgBody value) {
      if (customMsgBodyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        customMsgBody_ = value;
      } else {
        customMsgBodyBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <code>.protoObj.CustomMsgBody customMsgBody = 14;</code>
     */
    public Builder setCustomMsgBody(
        io.piper.common.pojo.message.protoObj.CustomMsgBody.Builder builderForValue) {
      if (customMsgBodyBuilder_ == null) {
        customMsgBody_ = builderForValue.build();
      } else {
        customMsgBodyBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <code>.protoObj.CustomMsgBody customMsgBody = 14;</code>
     */
    public Builder mergeCustomMsgBody(io.piper.common.pojo.message.protoObj.CustomMsgBody value) {
      if (customMsgBodyBuilder_ == null) {
        if (((bitField0_ & 0x00002000) != 0) &&
          customMsgBody_ != null &&
          customMsgBody_ != io.piper.common.pojo.message.protoObj.CustomMsgBody.getDefaultInstance()) {
          getCustomMsgBodyBuilder().mergeFrom(value);
        } else {
          customMsgBody_ = value;
        }
      } else {
        customMsgBodyBuilder_.mergeFrom(value);
      }
      if (customMsgBody_ != null) {
        bitField0_ |= 0x00002000;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.protoObj.CustomMsgBody customMsgBody = 14;</code>
     */
    public Builder clearCustomMsgBody() {
      bitField0_ = (bitField0_ & ~0x00002000);
      customMsgBody_ = null;
      if (customMsgBodyBuilder_ != null) {
        customMsgBodyBuilder_.dispose();
        customMsgBodyBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.protoObj.CustomMsgBody customMsgBody = 14;</code>
     */
    public io.piper.common.pojo.message.protoObj.CustomMsgBody.Builder getCustomMsgBodyBuilder() {
      bitField0_ |= 0x00002000;
      onChanged();
      return getCustomMsgBodyFieldBuilder().getBuilder();
    }
    /**
     * <code>.protoObj.CustomMsgBody customMsgBody = 14;</code>
     */
    public io.piper.common.pojo.message.protoObj.CustomMsgBodyOrBuilder getCustomMsgBodyOrBuilder() {
      if (customMsgBodyBuilder_ != null) {
        return customMsgBodyBuilder_.getMessageOrBuilder();
      } else {
        return customMsgBody_ == null ?
            io.piper.common.pojo.message.protoObj.CustomMsgBody.getDefaultInstance() : customMsgBody_;
      }
    }
    /**
     * <code>.protoObj.CustomMsgBody customMsgBody = 14;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.piper.common.pojo.message.protoObj.CustomMsgBody, io.piper.common.pojo.message.protoObj.CustomMsgBody.Builder, io.piper.common.pojo.message.protoObj.CustomMsgBodyOrBuilder> 
        getCustomMsgBodyFieldBuilder() {
      if (customMsgBodyBuilder_ == null) {
        customMsgBodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.piper.common.pojo.message.protoObj.CustomMsgBody, io.piper.common.pojo.message.protoObj.CustomMsgBody.Builder, io.piper.common.pojo.message.protoObj.CustomMsgBodyOrBuilder>(
                getCustomMsgBody(),
                getParentForChildren(),
                isClean());
        customMsgBody_ = null;
      }
      return customMsgBodyBuilder_;
    }

    private com.google.protobuf.Any body_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> bodyBuilder_;
    /**
     * <code>.google.protobuf.Any body = 15;</code>
     * @return Whether the body field is set.
     */
    public boolean hasBody() {
      return ((bitField0_ & 0x00004000) != 0);
    }
    /**
     * <code>.google.protobuf.Any body = 15;</code>
     * @return The body.
     */
    public com.google.protobuf.Any getBody() {
      if (bodyBuilder_ == null) {
        return body_ == null ? com.google.protobuf.Any.getDefaultInstance() : body_;
      } else {
        return bodyBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Any body = 15;</code>
     */
    public Builder setBody(com.google.protobuf.Any value) {
      if (bodyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
      } else {
        bodyBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Any body = 15;</code>
     */
    public Builder setBody(
        com.google.protobuf.Any.Builder builderForValue) {
      if (bodyBuilder_ == null) {
        body_ = builderForValue.build();
      } else {
        bodyBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Any body = 15;</code>
     */
    public Builder mergeBody(com.google.protobuf.Any value) {
      if (bodyBuilder_ == null) {
        if (((bitField0_ & 0x00004000) != 0) &&
          body_ != null &&
          body_ != com.google.protobuf.Any.getDefaultInstance()) {
          getBodyBuilder().mergeFrom(value);
        } else {
          body_ = value;
        }
      } else {
        bodyBuilder_.mergeFrom(value);
      }
      if (body_ != null) {
        bitField0_ |= 0x00004000;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Any body = 15;</code>
     */
    public Builder clearBody() {
      bitField0_ = (bitField0_ & ~0x00004000);
      body_ = null;
      if (bodyBuilder_ != null) {
        bodyBuilder_.dispose();
        bodyBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Any body = 15;</code>
     */
    public com.google.protobuf.Any.Builder getBodyBuilder() {
      bitField0_ |= 0x00004000;
      onChanged();
      return getBodyFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Any body = 15;</code>
     */
    public com.google.protobuf.AnyOrBuilder getBodyOrBuilder() {
      if (bodyBuilder_ != null) {
        return bodyBuilder_.getMessageOrBuilder();
      } else {
        return body_ == null ?
            com.google.protobuf.Any.getDefaultInstance() : body_;
      }
    }
    /**
     * <code>.google.protobuf.Any body = 15;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
        getBodyFieldBuilder() {
      if (bodyBuilder_ == null) {
        bodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                getBody(),
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      return bodyBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protoObj.Msg)
  }

  // @@protoc_insertion_point(class_scope:protoObj.Msg)
  private static final io.piper.common.pojo.message.protoObj.Msg DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.piper.common.pojo.message.protoObj.Msg();
  }

  public static io.piper.common.pojo.message.protoObj.Msg getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Msg>
      PARSER = new com.google.protobuf.AbstractParser<Msg>() {
    @java.lang.Override
    public Msg parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Msg> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Msg> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.piper.common.pojo.message.protoObj.Msg getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

