// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Msg.proto

// Protobuf Java Version: 3.25.3
package io.piper.common.pojo.message.protoObj;

public final class PBOuterClass {
  private PBOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protoObj_Msg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protoObj_Msg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protoObj_ImageMsgBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protoObj_ImageMsgBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protoObj_AudioMsgBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protoObj_AudioMsgBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protoObj_VideoMsgBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protoObj_VideoMsgBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protoObj_FileMsgBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protoObj_FileMsgBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protoObj_LocationMsgBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protoObj_LocationMsgBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protoObj_CustomMsgBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protoObj_CustomMsgBody_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017proto/Msg.proto\022\010protoObj\032\031google/prot" +
      "obuf/any.proto\"\265\003\n\003Msg\022\n\n\002id\030\001 \001(\003\022\014\n\004ty" +
      "pe\030\002 \001(\005\022\020\n\010chatType\030\003 \001(\005\022\016\n\006chatId\030\004 \001" +
      "(\003\022\014\n\004from\030\005 \001(\003\022\n\n\002to\030\006 \003(\003\022\014\n\004text\030\007 \001" +
      "(\t\022\014\n\004time\030\010 \001(\003\022,\n\014imageMsgBody\030\t \001(\0132\026" +
      ".protoObj.ImageMsgBody\022,\n\014audioMsgBody\030\n" +
      " \001(\0132\026.protoObj.AudioMsgBody\022,\n\014videoMsg" +
      "Body\030\013 \001(\0132\026.protoObj.VideoMsgBody\022*\n\013fi" +
      "leMsgBody\030\014 \001(\0132\025.protoObj.FileMsgBody\0222" +
      "\n\017locationMsgBody\030\r \001(\0132\031.protoObj.Locat" +
      "ionMsgBody\022.\n\rcustomMsgBody\030\016 \001(\0132\027.prot" +
      "oObj.CustomMsgBody\022\"\n\004body\030\017 \001(\0132\024.googl" +
      "e.protobuf.Any\"H\n\014ImageMsgBody\022\013\n\003url\030\001 " +
      "\001(\t\022\014\n\004size\030\002 \001(\005\022\r\n\005width\030\003 \001(\005\022\016\n\006heig" +
      "ht\030\004 \001(\005\":\n\014AudioMsgBody\022\013\n\003url\030\001 \001(\t\022\014\n" +
      "\004size\030\002 \001(\005\022\017\n\007seconds\030\003 \001(\005\"H\n\014VideoMsg" +
      "Body\022\013\n\003url\030\001 \001(\t\022\014\n\004size\030\002 \001(\005\022\017\n\007secon" +
      "ds\030\003 \001(\005\022\014\n\004name\030\004 \001(\t\"6\n\013FileMsgBody\022\013\n" +
      "\003url\030\001 \001(\t\022\014\n\004size\030\002 \001(\005\022\014\n\004name\030\003 \001(\t\"G" +
      "\n\017LocationMsgBody\022\017\n\007address\030\001 \001(\t\022\020\n\010la" +
      "titude\030\002 \001(\001\022\021\n\tlongitude\030\003 \001(\001\"\035\n\rCusto" +
      "mMsgBody\022\014\n\004data\030\001 \001(\tB:\n%io.piper.commo" +
      "n.pojo.message.protoObjB\014PBOuterClassP\001\370" +
      "\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_protoObj_Msg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protoObj_Msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protoObj_Msg_descriptor,
        new java.lang.String[] { "Id", "Type", "ChatType", "ChatId", "From", "To", "Text", "Time", "ImageMsgBody", "AudioMsgBody", "VideoMsgBody", "FileMsgBody", "LocationMsgBody", "CustomMsgBody", "Body", });
    internal_static_protoObj_ImageMsgBody_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protoObj_ImageMsgBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protoObj_ImageMsgBody_descriptor,
        new java.lang.String[] { "Url", "Size", "Width", "Height", });
    internal_static_protoObj_AudioMsgBody_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protoObj_AudioMsgBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protoObj_AudioMsgBody_descriptor,
        new java.lang.String[] { "Url", "Size", "Seconds", });
    internal_static_protoObj_VideoMsgBody_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_protoObj_VideoMsgBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protoObj_VideoMsgBody_descriptor,
        new java.lang.String[] { "Url", "Size", "Seconds", "Name", });
    internal_static_protoObj_FileMsgBody_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_protoObj_FileMsgBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protoObj_FileMsgBody_descriptor,
        new java.lang.String[] { "Url", "Size", "Name", });
    internal_static_protoObj_LocationMsgBody_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_protoObj_LocationMsgBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protoObj_LocationMsgBody_descriptor,
        new java.lang.String[] { "Address", "Latitude", "Longitude", });
    internal_static_protoObj_CustomMsgBody_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_protoObj_CustomMsgBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protoObj_CustomMsgBody_descriptor,
        new java.lang.String[] { "Data", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
