server:
  port: 8090
  profile: ${profile}

redis:
  host: localhost
  port: 6379
  password: "123456"
  timeout: 30000
  maxActive: 5000
  maxWait: 5000
  maxIdle: 100
  minIdle: 50

db:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/im
  username: root
  password: "123456"
