server:
  port: 8090

jwt:
  secret: 7Rv9OTzS
  expireHour: 24
  name: token

redis:
  host: localhost
  port: 6379
  password: "123456"
  timeout: 30000
  maxActive: 5000
  maxWait: 5000
  maxIdle: 100
  minIdle: 50
