spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/h2-schema.sql
    data: classpath:db/h2-data.sql
    url: jdbc:h2:mem:im
    username: sa
    password: sa

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
