server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/html
spring:
  profiles:
    active: ${profile}
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 35MB

logging:
  config: classpath:log4j2.xml
  level:
    root: info

mybatis:
  type-aliases-package: io.piper.server.spring.pojo.entity
  mapper-locations: classpath:io/piper/server/spring/pojo/mapper/xml/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
