spring:
  datasource:
    url: jdbc:mysql://localhost:3306/im
    username: root
    password: "123456"
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    pool:
      max-active: 3
