spring:
  h2:
    console:
      enabled: true
      webAllowOthers: true
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/h2-schema.sql
    data: classpath:db/h2-data.sql
    url: jdbc:h2:mem:im
    username: root
    password: "123456"
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 3000
    pool:
      min-idle: 3
      max-idle: 10
      max-active: 100
      max-wait: 3000

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
